"""
does_list_contain_two_summands takes a list of integers and a target integer, and returns true if the list contains two numbers which sum to the target

it is currently stubbed out and the unit test is failing. please fill in some code to make the test pass, and then add some more unit tests

submitted by ben.solwitz@nytimes.com, updated to python by eric.perrotta@nytimes.com
"""

def does_list_contain_two_summands(summands, target):
    return False

assert does_list_contain_two_summands([2, 4, 3], 5) == True

print("Successfully passed all tests!")
